# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.TextField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
