# Generated by Django 2.2 on 2019-08-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='brewery',
            field=models.TextField(blank=True),
        ),
    ]
